### ISSUE TITLE
TypeError: assert_series_equal() got an unexpected keyword argument 'rtol'

### ISSUE THREAD

**Issue by AlfredWGA** [jbesomi/texthero#187]
I clone the latest repo and run `python -m unittest discover -s tests -t .` locally, but getting errors like the following,

```
ERROR: test_dim_reduction_and_clustering_with_documenttermDF_input_0_pca (tests.test_representation.AbstractRepresentationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\anaconda3\envs\texthero\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\Alfred Wei\Desktop\texthero\tests\test_representation.py", line 257, in test_dim_reduction_and_clustering_with_documenttermDF_input
    check_category_order=False,
TypeError: assert_series_equal() got an unexpected keyword argument 'rtol'

======================================================================
ERROR: test_dim_reduction_and_clustering_with_documenttermDF_input_1_nmf (tests.test_representation.AbstractRepresentationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\anaconda3\envs\texthero\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\Alfred Wei\Desktop\texthero\tests\test_representation.py", line 257, in test_dim_reduction_and_clustering_with_documenttermDF_input
    check_category_order=False,
TypeError: assert_series_equal() got an unexpected keyword argument 'rtol'
...
```

Seems like something to do with `pd.testing.assert_series_equal`. I am using `pandas==1.0.5` as `pandas>=1.0.2` requires, and Win10, why is this happening?

**Comment by henrifroese** [comment]
Hmm, as far as I can see this does have to do with the Pandas version; we might need to increase the minimum required version for the developer dependencies. I'll look into it

**Comment by henrifroese** [comment]
Just saw [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.testing.assert_series_equal.html) that it was added in version 1.1.0, so we'll need to increase the dev dependency to that 👌💡

**Comment by AlfredWGA** [comment]
@henrifroese Thanks for the solution!
